# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: idm.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'idm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tidm.proto\x12\x13\x63om.POSproject.grpc\"U\n\x0fRegisterRequest\x12\x13\n\x0b\x61\x64min_token\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"/\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\"\"\n\x11\x43heckTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"@\n\x12\x43heckTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"$\n\x13\x44\x65stroyTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\'\n\x14\x44\x65stroyTokenResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\rDeleteRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"5\n\rUpdateRequest\x12\x11\n\told_email\x18\x01 \x01(\t\x12\x11\n\tnew_email\x18\x02 \x01(\t\"!\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb0\x04\n\x0b\x41uthService\x12[\n\x0cRegisterUser\x12$.com.POSproject.grpc.RegisterRequest\x1a%.com.POSproject.grpc.RegisterResponse\x12R\n\tLoginUser\x12!.com.POSproject.grpc.LoginRequest\x1a\".com.POSproject.grpc.LoginResponse\x12]\n\nCheckToken\x12&.com.POSproject.grpc.CheckTokenRequest\x1a\'.com.POSproject.grpc.CheckTokenResponse\x12\x63\n\x0c\x44\x65stroyToken\x12(.com.POSproject.grpc.DestroyTokenRequest\x1a).com.POSproject.grpc.DestroyTokenResponse\x12U\n\nDeleteUser\x12\".com.POSproject.grpc.DeleteRequest\x1a#.com.POSproject.grpc.DeleteResponse\x12U\n\nUpdateUser\x12\".com.POSproject.grpc.UpdateRequest\x1a#.com.POSproject.grpc.UpdateResponseB\x1d\n\x13\x63om.POSproject.grpcB\x04\x41uthP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'idm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.POSproject.grpcB\004AuthP\001'
  _globals['_REGISTERREQUEST']._serialized_start=34
  _globals['_REGISTERREQUEST']._serialized_end=119
  _globals['_REGISTERRESPONSE']._serialized_start=121
  _globals['_REGISTERRESPONSE']._serialized_end=156
  _globals['_LOGINREQUEST']._serialized_start=158
  _globals['_LOGINREQUEST']._serialized_end=205
  _globals['_LOGINRESPONSE']._serialized_start=207
  _globals['_LOGINRESPONSE']._serialized_end=254
  _globals['_CHECKTOKENREQUEST']._serialized_start=256
  _globals['_CHECKTOKENREQUEST']._serialized_end=290
  _globals['_CHECKTOKENRESPONSE']._serialized_start=292
  _globals['_CHECKTOKENRESPONSE']._serialized_end=356
  _globals['_DESTROYTOKENREQUEST']._serialized_start=358
  _globals['_DESTROYTOKENREQUEST']._serialized_end=394
  _globals['_DESTROYTOKENRESPONSE']._serialized_start=396
  _globals['_DESTROYTOKENRESPONSE']._serialized_end=435
  _globals['_DELETEREQUEST']._serialized_start=437
  _globals['_DELETEREQUEST']._serialized_end=467
  _globals['_DELETERESPONSE']._serialized_start=469
  _globals['_DELETERESPONSE']._serialized_end=502
  _globals['_UPDATEREQUEST']._serialized_start=504
  _globals['_UPDATEREQUEST']._serialized_end=557
  _globals['_UPDATERESPONSE']._serialized_start=559
  _globals['_UPDATERESPONSE']._serialized_end=592
  _globals['_AUTHSERVICE']._serialized_start=595
  _globals['_AUTHSERVICE']._serialized_end=1155
# @@protoc_insertion_point(module_scope)
