// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "idm.proto" (package "com.POSproject.grpc", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuthService } from "./idm";
import type { UpdateResponse } from "./idm";
import type { UpdateRequest } from "./idm";
import type { DeleteResponse } from "./idm";
import type { DeleteRequest } from "./idm";
import type { DestroyTokenResponse } from "./idm";
import type { DestroyTokenRequest } from "./idm";
import type { CheckTokenResponse } from "./idm";
import type { CheckTokenRequest } from "./idm";
import type { LoginResponse } from "./idm";
import type { LoginRequest } from "./idm";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { RegisterResponse } from "./idm";
import type { RegisterRequest } from "./idm";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service com.POSproject.grpc.AuthService
 */
export interface IAuthServiceClient {
    /**
     * @generated from protobuf rpc: RegisterUser(com.POSproject.grpc.RegisterRequest) returns (com.POSproject.grpc.RegisterResponse);
     */
    registerUser(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: LoginUser(com.POSproject.grpc.LoginRequest) returns (com.POSproject.grpc.LoginResponse);
     */
    loginUser(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse>;
    /**
     * @generated from protobuf rpc: CheckToken(com.POSproject.grpc.CheckTokenRequest) returns (com.POSproject.grpc.CheckTokenResponse);
     */
    checkToken(input: CheckTokenRequest, options?: RpcOptions): UnaryCall<CheckTokenRequest, CheckTokenResponse>;
    /**
     * @generated from protobuf rpc: DestroyToken(com.POSproject.grpc.DestroyTokenRequest) returns (com.POSproject.grpc.DestroyTokenResponse);
     */
    destroyToken(input: DestroyTokenRequest, options?: RpcOptions): UnaryCall<DestroyTokenRequest, DestroyTokenResponse>;
    /**
     * @generated from protobuf rpc: DeleteUser(com.POSproject.grpc.DeleteRequest) returns (com.POSproject.grpc.DeleteResponse);
     */
    deleteUser(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse>;
    /**
     * @generated from protobuf rpc: UpdateUser(com.POSproject.grpc.UpdateRequest) returns (com.POSproject.grpc.UpdateResponse);
     */
    updateUser(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse>;
}
/**
 * @generated from protobuf service com.POSproject.grpc.AuthService
 */
export class AuthServiceClient implements IAuthServiceClient, ServiceInfo {
    typeName = AuthService.typeName;
    methods = AuthService.methods;
    options = AuthService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: RegisterUser(com.POSproject.grpc.RegisterRequest) returns (com.POSproject.grpc.RegisterResponse);
     */
    registerUser(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, RegisterResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: LoginUser(com.POSproject.grpc.LoginRequest) returns (com.POSproject.grpc.LoginResponse);
     */
    loginUser(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginRequest, LoginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CheckToken(com.POSproject.grpc.CheckTokenRequest) returns (com.POSproject.grpc.CheckTokenResponse);
     */
    checkToken(input: CheckTokenRequest, options?: RpcOptions): UnaryCall<CheckTokenRequest, CheckTokenResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CheckTokenRequest, CheckTokenResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DestroyToken(com.POSproject.grpc.DestroyTokenRequest) returns (com.POSproject.grpc.DestroyTokenResponse);
     */
    destroyToken(input: DestroyTokenRequest, options?: RpcOptions): UnaryCall<DestroyTokenRequest, DestroyTokenResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DestroyTokenRequest, DestroyTokenResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteUser(com.POSproject.grpc.DeleteRequest) returns (com.POSproject.grpc.DeleteResponse);
     */
    deleteUser(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteRequest, DeleteResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateUser(com.POSproject.grpc.UpdateRequest) returns (com.POSproject.grpc.UpdateResponse);
     */
    updateUser(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateRequest, UpdateResponse>("unary", this._transport, method, opt, input);
    }
}
